version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.18
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_TOKEN: root
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    command: |
      vault server -dev -dev-root-token-id=root &
      sleep 5
      sh /vault/scripts/init-secrets.sh
      tail -f /dev/null
    volumes:
      - ./vault/data:/vault/file
      - ./scripts:/vault/scripts
