services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: donghyun
      MINIO_ROOT_PASSWORD: donghyun
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - mlflow-net

volumes:
  minio_data:

networks:
  mlflow-net:
    external: true