services:
  postgres:
    image: postgres:14
    container_name: mlflow-postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflowpass
      POSTGRES_DB: mlflow_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - mlflow-net

  mlflow:
    build:
      context: .
      dockerfile: mlflow.Dockerfile
    image: mlflow:latest
    container_name: mlflow
    # ports:
    #   - "5000:5000"
    environment:
      AWS_ACCESS_KEY_ID: donghyun
      AWS_SECRET_ACCESS_KEY: donghyun
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: >
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflowpass@postgres:5432/mlflow_db
      --default-artifact-root s3://mlflow-artifacts/
      --host 0.0.0.0
      --port 5000
    depends_on:
      - postgres
    networks:
      - mlflow-net

  nginx:
    image: nginx:latest
    container_name: mlflow-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - mlflow
    networks:
      - mlflow-net

volumes:
  postgres_data:

networks:
  mlflow-net:
    driver: bridge