{
 "title": "Node Resource",
 "description": "Batch of nearly all metrics values exported by Prometheus and Node Exporter.",
 "tags": [
  "node_exporter",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_uname_info,nodename)"
    }
   },
   {
    "name": "instance",
    "label": "인스턴스 IP",
    "query": {
     "query": "query_result(node_uname_info{nodename=\"$node\"})"
    }
   },
   {
    "name": "device",
    "query": "label_values(node_network_receive_bytes_total, device)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_boot_time_seconds,job)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU / Memory / Disk Gauge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Busy",
   "type": "stat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$instance\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$instance\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$instance\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "stat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"$instance\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "stat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$instance\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "stat",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$instance\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=\"$instance\",job=~\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$instance\",job=~\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "stat",
   "description": "The root filesystem is the filesystem that is contained on the same partition on which the root directory is located",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$instance\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$instance\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=\"$instance\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=\"$instance\"} )/ node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$instance\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "( (node_memory_MemFree_bytes{instance=\"$instance\"} + node_memory_Cached_bytes{instance=\"$instance\"} + node_memory_Slab_bytes{instance=\"$instance\"} + node_memory_Buffers_bytes{instance=\"$instance\"} ) / node_memory_MemTotal_bytes{instance=\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU / Memory / Disk Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$instance\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\",job=~\"$job\"} - node_boot_time_seconds{instance=\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "stat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"$instance\", device=~\"/dev/.*\"})"
    }
   ]
  },
  {
   "title": "System Load (5m avg)",
   "type": "stat",
   "description": "System Load (5m avg)",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{instance=\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU / Memory Graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{instance=\"$instance\",job=~\"$job\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\",job=~\"$job\"} - node_memory_MemFree{instance=\"$instance:$port\",job=~\"$job\"} - (node_memory_Cached{instance=\"$instance:$port\",job=~\"$job\"} + node_memory_Buffers{instance=\"$instance:$port\",job=~\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\",job=~\"$job\"} + node_memory_Buffers{instance=\"$instance:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\",job=~\"$job\"} - node_memory_SwapFree{instance=\"$instance:$port\",job=~\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\",job=~\"$job\"} - node_memory_MemFree_bytes{job='node',instance='$instance'} - node_memory_Buffers_bytes{job='node',instance='$instance'} - node_memory_Cached_bytes{job='node',instance='$instance'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=\"$instance\",job=~\"$job\"} - node_memory_Buffers_bytes{instance=\"$instance\",job=~\"$job\"} - node_memory_Cached_bytes{instance=\"$instance\",job=~\"$job\"} - node_memory_Slab_bytes{instance=\"$instance\",job=~\"$job\"} - node_memory_PageTables_bytes{instance=\"$instance\",job=~\"$job\"} - node_memory_SwapCached_bytes{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "Unused - Free memory unasigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\",job=~\"$job\"} - node_memory_SwapFree{instance=\"$instance\",job=~\"$job\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$instance\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Disk Graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",job=~\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$instance\",job=~\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$instance\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$instance\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "Filesystem Fullness",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{instance=\"$instance\",job=~\"$job\",fstype!='rootfs',mountpoint!~'/images/',mountpoint!=''} / node_filesystem_size_bytes{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",job=~\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$instance\",job=~\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_load1{instance=\"$instance\"})",
       "legendFormat": "load1"
      },
      {
       "expr": "sum(node_load5{instance=\"$instance\"})",
       "legendFormat": "load5"
      },
      {
       "expr": "sum(node_load15{instance=\"$instance\"})",
       "legendFormat": "load15"
      }
     ]
    },
    {
     "title": "Network Traffic (eth0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes", "label": "bits in (-) / bits out (+)" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{device=\"eth0\",instance=\"dverbcen02.rouen.francetelecom.fr:9100\",job=\"node\"}[1m]))",
       "legendFormat": "in"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{device=\"eth0\",instance=\"dverbcen02.rouen.francetelecom.fr:9100\",job=\"node\"}[1m]))",
       "legendFormat": "out"
      }
     ]
    },
    {
     "title": "Network Utillization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes", "label": "bits in (-) / bits out (+)" }
     ],
     "targets": [
      {
       "expr": "sum(increase(node_network_receive_bytes_total{device=~\"$device\",instance=\"$instance\"}[1m]))",
       "legendFormat": "in"
      },
      {
       "expr": "sum(increase(node_network_transmit_bytes_total{device=~\"$device\",instance=\"$instance\"}[1m]))",
       "legendFormat": "out"
      }
     ]
    },
    {
     "title": "Traffic In",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
     "format": "decbytes",
     "valueName": "max",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(node_network_receive_bytes_total{device=~\"$device\",instance=\"$instance\"}[24h]))"
      }
     ]
    },
    {
     "title": "Traffic Out",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
     "format": "bytes",
     "valueName": "max",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(node_network_transmit_bytes_total{device=~\"$device\",instance=\"$instance\"}[24h]))"
      }
     ]
    },
    {
     "title": "Netstat: TCP",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_netstat_Tcp_CurrEstab{instance=\"$instance\"})",
       "legendFormat": "established"
      },
      {
       "expr": "sum(node_netstat_Tcp_ActiveOpens{instance=\"$instance\"})",
       "legendFormat": "activeOpens"
      },
      {
       "expr": "sum(node_netstat_Tcp_PassiveOpens{instance=\"$instance\"})",
       "legendFormat": "passiveOpens"
      },
      {
       "expr": "sum(node_netstat_Tcp_EstabResets{instance=\"$instance\"})",
       "legendFormat": "estabResets"
      },
      {
       "expr": "sum(node_netstat_Tcp_AttemptFails{instance=\"$instance\"})",
       "legendFormat": "attemptfails"
      },
      {
       "expr": "sum(node_netstat_Tcp_RetransSegs{instance=\"$instance\"})",
       "legendFormat": "retransSegs"
      }
     ]
    },
    {
     "title": "Netstat: UDP",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_netstat_Udp_InDatagrams{instance=\"$instance\"}[5m]))",
       "legendFormat": "Udp_InDatagrams"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_InErrors{instance=\"$instance\"}[5m]))",
       "legendFormat": "Udp_InErrors"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_OutDatagrams{instance=\"$instance\"}[5m]))",
       "legendFormat": "Udp_OutDatagrams"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_NoPorts{instance=\"$instance\"}[5m]))",
       "legendFormat": "Udp_NoPorts"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_InCsumErrors{instance=\"$instance\"}[5m]))",
       "legendFormat": "Udp_InCsumErrors"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_RcvbufErrors{instance=\"$instance\"}[5m]))",
       "legendFormat": "Udp_RcvbufErrors"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_SndbufErrors{instance=\"$instance\"}[5m]))",
       "legendFormat": "Udp_SndbufErrors"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{instance=\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(irate(node_network_transmit_bytes_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{instance=\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Receive drop"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{instance=\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Transmit drop"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{instance=\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Rransmit errors"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
    },
    {
     "expr": "node_netstat_Tcp_InErrs{instance=\"$instance\",job=~\"$job\"}",
     "legendFormat": "InErrs"
    }
   ]
  },
  {
   "title": "Network Traffic Fifo",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_fifo_total{instance=\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Receive fifo"
    },
    {
     "expr": "irate(node_network_transmit_fifo_total{instance=\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Transmit fifo"
    }
   ]
  },
  {
   "title": "Prometheus / Node / Scraps  Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Exporter Build Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_build_info",
     "legendFormat": "Prometheus Version: {{version}}"
    },
    {
     "expr": "node_exporter_build_info",
     "legendFormat": "Node-Exporter Version: {{version}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "scrape_collector_duration",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_scrape_collector_duration_seconds{job=\"node\",instance=\"$instance\"}",
     "legendFormat": "{{collector}}"
    }
   ]
  }
 ]
}