global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'custom-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['custom-exporter:8080']
rule_files:
  - /etc/prometheus/alert.rules.yml
