services:

  grafana:
    image: grafana/grafana:latest
    build:
      context: ./grafana
    container_name: grafana
    volumes:
      - ./local_home/grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    networks:
      - prometheus
    user: '1000'

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - prometheus

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - ./grafana/promtail/config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
      - ./local_home/flog_data:/logs
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - prometheus

  flog:
    image: mingrammer/flog
    container_name: flog
    command: -f json -o '/var/log/dump.log' -d 5s -l -t log -w
    volumes:
      - ./local_home/flog_data:/var/log
    networks:
      - prometheus

networks:
  prometheus:
    external: True
    name: prometheus