all:
  hosts:
    master:
      ansible_host: 192.168.0.8
      ip: 192.168.0.8
      access_ip: 192.168.0.8
    worker1:
      ansible_host: 192.168.0.7
      ip: 192.168.0.7
      access_ip: 192.168.0.7
    worker2:
      ansible_host: 192.168.0.6
      ip: 192.168.0.6
      access_ip: 192.168.0.6
    worker3:
      ansible_host: 192.168.0.9
      ip: 192.168.0.9
      access_ip: 192.168.0.9
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        worker1:
        worker2:
        worker3:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
