apiVersion: v1
kind: Service
metadata:
  # Expose the management HTTP port on each node
  namespace: rabbit
  name: rabbitmq-management
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 15672
    name: http
    targetPort: 15672
  externalIPs:
    - 192.168.10.5
  #type: LoadBalancer # Or LoadBalancer in production w/ proper security
---
apiVersion: v1
kind: Service
metadata:
  # The required headless service for StatefulSets
  namespace: rabbit
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
    name: amqp
    targetPort: 5672
  - port: 4369
    name: epmd
  - port: 25672
    name: rabbitmq-dist
  #externalIPs:
  # - 172.16.113.205
  selector:
    app: rabbitmq
  type: ClusterIP
