
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-env
data:
  log_level: "INFO"
  RABBITMQ_URL: 192.168.0.8:5674
  DATABASE_URL: mqsql://localhost:3306/db
  app.config: |
    name=donghyun
    desc=test