
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu:2404
      command: ["$(NVIDIA_SMI)"]
      envFrom:
        - configRef:
            name: config-cmd