global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'dcgm-exporter'
    static_configs:
      - targets: ['dcgm-exporter:9400']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'custom-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:8080']
  
rule_files:
  - /etc/prometheus/alert.rules.yml
