---
- name: Configure auto login for Ubuntu server
  hosts: all
  become: yes
  tasks:
    - name: Create directory for getty@tty1 override
      file:
        path: /etc/systemd/system/getty@tty1.service.d
        state: directory
        mode: '0755'

    - name: Set up auto login configuration for getty@tty1
      copy:
        dest: /etc/systemd/system/getty@tty1.service.d/override.conf
        content: |
          [Service]
          ExecStart=
          ExecStart=-/sbin/agetty --autologin {{ username }} -o '-p -- \\u' --noclear %I $TERM
        mode: '0644'
      vars:
        username: "donghyun"
        
    - name: Reload systemd daemon to recognize changes
      command: systemctl daemon-reload

    - name: Restart getty@tty1 service to apply auto login settings
      systemd:
        name: getty@tty1
        state: restarted
