---
- name: Initialize Kubernetes Master
  hosts: masters
  become: yes
  tasks: 
    - name: Init ansible facts
      set_fact:
        HOME: "/home/donghyun"
    
    - name: Initialize Kubernetes master node
      command: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.0.8
      register: master_output

    - name: Save kubeconfig for the user
      shell: |
        rm -rf {{ HOME }}/.kube
        mkdir -p {{ HOME }}/.kube
        cp -i /etc/kubernetes/admin.conf {{ HOME }}/.kube/config
        chown $(id -u):$(id -g) {{ HOME }}/.kube/config
        chmod 666 {{ HOME }}/.kube/config

    - name: Display the join command
      debug:
        msg: "{{ master_output.stdout_lines | select('search', 'kubeadm join') | list }}"
      register: join_command

    - name: Set join command as a fact for use in worker nodes
      set_fact:
        join_command: "{{ master_output.stdout_lines | select('search', 'kubeadm join') | list | first }}"

- name: Join worker nodes to the cluster
  hosts: workers
  become: yes
  tasks:
    - name: Display the join command
      debug:
        msg: "{{ hostvars['donghyun'].join_command }}"
    
    # - name: Temp
    #   debug:
    #     msg: "{{join_command}}"

    # - name: Wait for the join command to be available
    #   wait_for:
    #     path: "{{ hostvars['master'].join_command | default([]) }}"
    #     timeout: 300
    #   delegate_to: localhost

    # - name: Display join command for workers
    #   debug:
    #     msg: "{{ hostvars['master'].join_command.msg | first }}"
    #   when: hostvars['master'].join_command is defined

    # - name: Join the worker node to the Kubernetes cluster
    #   command: "{{ hostvars['master'].join_command.msg | first }}"
    #   when: hostvars['master'].join_command is defined
    #   register: join_result

    # - name: Show join command result
    #   debug:
    #     msg: "{{ join_result.stdout }}"