---
- name: Initialize Kubernetes Master
  hosts: masters
  become: yes
  tasks: 
    - name: Init ansible facts
      set_fact:
        HOME: "/home/donghyun"
    
    - name: Initialize Kubernetes master node
      command: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.0.8
      register: master_output

    - name: Save kubeconfig for the user
      shell: |
        rm -rf {{ HOME }}/.kube
        mkdir -p {{ HOME }}/.kube
        cp -f /etc/kubernetes/admin.conf {{ HOME }}/.kube/config
        chown $(id -u):$(id -g) {{ HOME }}/.kube/config
        chmod 666 {{ HOME }}/.kube/config

    - name: Generate kubeadm join command
      shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        kubeadm token create --print-join-command
      register: join_command

    - name: Display the join command
      debug:
        msg: "{{ join_command.stdout }}"

- name: Join worker nodes to the cluster
  hosts: workers
  become: yes
  tasks:
    - name: Display the join command
      debug:
        msg: "{{ hostvars['donghyun'].join_command }}"
    
    - name: Join the worker node to the Kubernetes cluster
      command: "{{ hostvars['donghyun'].join_command.stdout }}"
      when: hostvars['donghyun'].join_command.stdout is defined
      register: join_result

    - name: Show join command result
      debug:
        msg: "{{ join_result.stdout }}"