---
- name: Enable root login on workers
  hosts: all
  become: yes  # root 권한으로 실행
  tasks:
    - name: Ensure PermitRootLogin is yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin yes'
        state: present
      
    - name: Restart SSH service
      systemd:
        name: sshd
        state: restarted