apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu:22.04
      command: ["/bin/bash", "-c", "sleep 360"]
      volumeMounts:
        - mountPath: "/mnt/data"
          name: hostpath-volume
  volumes:
    - name: hostpath-volume
      persistentVolumeClaim:
        claimName: hostpath-pvc