# nfs-pv.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadOnlyMany                     # ROX: 여러 노드에서 '읽기' 전용으로 접근 가능.
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/shared/                 # nfs 서버에 공유 디렉토리가 생성되어 있어야 함. 
    server: 192.168.0.8